Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -14,14 +14,14 @@ jobs:
     steps:
     - uses: actions/checkout@v4
     
-    - name: Verify input directory
-      run: |
-        if [ ! -d "${{ inputs.input_directory }}" ]; then
-          echo "Input directory not found: ${{ inputs.input_directory }}"
-          exit 1
-        fi
-        echo "Using source code from: ${{ inputs.input_directory }}"
-        ls -la ${{ inputs.input_directory }}
+    # - name: Verify input directory
+    #   run: |
+    #     if [ ! -d "${{ inputs.input_directory }}" ]; then
+    #       echo "Input directory not found: ${{ inputs.input_directory }}"
+    #       exit 1
+    #     fi
+    #     echo "Using source code from: ${{ inputs.input_directory }}"
+    #     ls -la ${{ inputs.input_directory }}
         
     - name: Run codeglide
       uses: madhavi-opsera/aicodegen@v23
